# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            coding @ jandavid
tagline:          'Learn from my fails'
description:      'Documentation of my software development endeavors. Expect a lot of TDD and Ruby.'

url:              http://coding.jandavid.de
baseurl:          /

author:
  name:           'Jan David'
  url:            https://twitter.com/mostawesomejd

paginate:         5

# Custom vars
enable_analytics: true
enable_disqus:    true

github:
  repo:           https://github.com/jdno

gems:             [jekyll-gist, jekyll-paginate]

# Links
links:
  docker:         '**[Docker](https://docker.com)**'
  docker-compose: '**[docker-compose](http://www.docker.com/products/docker-compose)**'
  docker-machine: '**[docker-machine](https://docs.docker.com/machine/)**'
  sinatra:        '**[Sinatra](http://sinatrarb.com)**'
